pipeline {
    agent any

    environment {
        def KUBECONFIG_CREDENTIAL_ID = 'dev-kubeconfig'
        def K8S_NAMESPACE = 'evc-dev'
        def PROJECT_NAME = "evc"
        def SERVICE_NAME = 'evc-steve'
        def HELM_FOLDER = "./evc-helm/dev/evc-ocpp/evc-steve"
        def HELM_VALUES_FILE = "values.yaml"
		def ENV_FILE = './src/main/resources/application-kubernetes.properties'

		def APP_REPO = "git@github.com:tdtuan97/echarge-steve.git"
		def PROJECT = "evc"
		def APP = "steve"
		def REPOSITORY_URI = "https://ghcr.io"
		def IMAGE_REPO_NAME="${PROJECT}/${env.BRANCH_NAME}/${SERVICE_NAME}"
		def BUILD_DATE = sh(script: 'date +"%Y-%m-%d"', returnStdout: true).trim()
		def IMAGE_TAG = "${BUILD_DATE}-build-${env.BUILD_NUMBER}"
		def REGISTRY_IMAGE = "ghcr.io/tdtuan97/${IMAGE_REPO_NAME}"
		def GITHUB_TOKEN = ""
		def GITHUB_CREDENTIAL = "github-sshkey"
		def GITHUB_TOKEN_CREDENTIAL_ID = 'github-token'

        def DB_OCPP_HOST_ID     = 'dev-database-host'
        def DB_OCPP_ACCOUNT_ID  = 'dev-database-account'
        def DB_DATABASE         = 'ocpp_stevedb'

        // NATS CREDENTIALS
        def NATS_ACCOUNT_ID = 'dev-nats-account'

        // APP CREDENTIALS
        def AUTH_USER     = 'evc'
        def AUTH_PASSWORD = 'evc2023'
        def WEB_API_KEY = 'evc'
        def WEB_API_VALUE = 'evc2023'
    }

    stages {
        stage('Set Environment Variables for main') {
            when {
                branch 'main'
            }
            steps {
                script {
                    KUBECONFIG_CREDENTIAL_ID = 'evc-prod-kubeconfig'
                    K8S_NAMESPACE = 'evc-prod'
                    HELM_FOLDER = "./evc-helm/prod/evc-ocpp/evc-steve"
                    ENV_FILE = './src/main/resources/application-kubernetes.properties'

                    DB_OCPP_HOST_ID = 'evc-prod-db-ocpp-host'
                    DB_OCPP_ACCOUNT_ID = 'evc-prod-db-ocpp-account'
                    DB_DATABASE = 'ocpp_stevedb'

                    NATS_ACCOUNT_ID = 'evc-prod-nats-account'

                    AUTH_USER = 'evc'
                    AUTH_PASSWORD = 'st3wEZS78izkyyBA'
                    WEB_API_KEY = 'evc'
                    WEB_API_VALUE = 'st3wEZS78izkyyBA'
                }
            }
        }

        stage('Cloning Git') {
		    steps {
		        echo "Clone git repository from branch: ${env.BRANCH_NAME}"
		        checkout(
		            [
		                $class: 'GitSCM',
		                branches: [[name: "*/${env.BRANCH_NAME}"]],
		                doGenerateSubmoduleConfigurations: false,
		                extensions: [],
		                submoduleCfg: [],
		                userRemoteConfigs: [
		                    [
		                        credentialsId: env.GITHUB_CREDENTIAL,
		                        url: "$APP_REPO"
		                    ]
		                ]
		            ]
		        )
		    }
		}

        stage('Build & Push docker image to registry') {
            steps {
                script {
                    env.BUILD_DATE = sh(script: 'date +"%Y-%m-%d"', returnStdout: true).trim()
                    env.IMAGE_TAG = "${env.BUILD_DATE}-build-${env.BUILD_NUMBER}"
                }
                script {
                    withCredentials([string(credentialsId: env.GITHUB_TOKEN_CREDENTIAL_ID, variable: 'GITHUB_TOKEN')]) {
                        sh "echo \$GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin"
                    }
                }
                script {
                    echo "Pull latest image."
                    docker.withRegistry(env.REPOSITORY_URI) {
                        sh "docker pull ${env.REGISTRY_IMAGE}:latest || true"
                    }
                }
                script {
                    withCredentials([
                        usernamePassword(
                            credentialsId: env.DB_OCPP_HOST_ID,
                            usernameVariable: 'OCPP_DB_HOST',
                            passwordVariable: 'OCPP_DB_PORT',
                        ),
                        usernamePassword(
                            credentialsId: env.DB_OCPP_ACCOUNT_ID,
                            usernameVariable: 'OCPP_DB_USER',
                            passwordVariable: 'OCPP_DB_PASS',
                        ),
                    ]) {
                        docker.withRegistry(env.REPOSITORY_URI) {
                            sh """
                                docker build \\
                                    --build-arg DB_HOST=\${OCPP_DB_HOST} \\
                                    --build-arg DB_PORT=\${OCPP_DB_PORT} \\
                                    --build-arg DB_USERNAME=\${OCPP_DB_USER} \\
                                    --build-arg DB_PASSWORD=\${OCPP_DB_PASS} \\
                                    --build-arg DB_DATABASE=\${DB_DATABASE} \\
                                    --cache-from ${env.REGISTRY_IMAGE}:latest \\
                                    -f k8s/docker/Dockerfile \\
                                    -t ${env.REGISTRY_IMAGE}:${env.IMAGE_TAG} \\
                                    -t ${env.REGISTRY_IMAGE}:latest \\
                                    .
                            """
                            dockerImage = docker.image("${env.REGISTRY_IMAGE}:${env.IMAGE_TAG}")
                            dockerImage.push("${env.IMAGE_TAG}")
                            dockerImage.push('latest')
                        }
                    }
                }
            }
        }

        stage('Remove docker image tag') {
            steps {
                script {
                    sh """
                        docker images --filter=reference="${env.REGISTRY_IMAGE}" --filter=dangling=true --quiet | xargs -r docker image rm
                    """
                }
            }
        }

        stage('Generate .env & Apply ConfigMap') {
            steps {
                withCredentials([
                    usernamePassword(
                        credentialsId: env.DB_OCPP_HOST_ID,
                        usernameVariable: 'OCPP_DB_HOST',
                        passwordVariable: 'OCPP_DB_PORT',
                    ),
                    usernamePassword(
                        credentialsId: env.DB_OCPP_ACCOUNT_ID,
                        usernameVariable: 'OCPP_DB_USER',
                        passwordVariable: 'OCPP_DB_PASS',
                    ),
                    usernamePassword(
                        credentialsId: env.NATS_ACCOUNT_ID,
                        usernameVariable: 'NATS_USERNAME',
                        passwordVariable: 'NATS_PASSWORD',
                    ),
                ]) {
                    sh """
                        rm -f application-kubernetes.properties
                        cp ${env.ENV_FILE} application-kubernetes.properties

                        sed -i 's|{OCPP_DB_HOST}|${OCPP_DB_HOST}|g' application-kubernetes.properties
                        sed -i 's|{OCPP_DB_PORT}|${OCPP_DB_PORT}|g' application-kubernetes.properties
                        sed -i 's|{OCPP_DB_USER}|${OCPP_DB_USER}|g' application-kubernetes.properties
                        sed -i 's|{OCPP_DB_PASS}|${OCPP_DB_PASS}|g' application-kubernetes.properties

                        sed -i 's|{AUTH_USER}|${AUTH_USER}|g' application-kubernetes.properties
                        sed -i 's|{AUTH_PASSWORD}|${AUTH_PASSWORD}|g' application-kubernetes.properties
                        sed -i 's|{WEB_API_KEY}|${WEB_API_KEY}|g' application-kubernetes.properties
                        sed -i 's|{WEB_API_VALUE}|${WEB_API_VALUE}|g' application-kubernetes.properties

                        sed -i 's|{NATS_USERNAME}|${NATS_USERNAME}|g' application-kubernetes.properties
                        sed -i 's|{NATS_PASSWORD}|${NATS_PASSWORD}|g' application-kubernetes.properties   
                    """
                }
                withCredentials([file(credentialsId: env.KUBECONFIG_CREDENTIAL_ID, variable: 'KUBECONFIG')]) {
                    sh """
                        export KUBECONFIG=\${KUBECONFIG}
                        kubectl delete configmap ${env.SERVICE_NAME}-env -n ${env.K8S_NAMESPACE} --ignore-not-found
                        kubectl create configmap ${env.SERVICE_NAME}-env --from-file=application-kubernetes.properties=application-kubernetes.properties -n ${env.K8S_NAMESPACE}
                    """
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                dir('infra') {
                    git credentialsId: 'github-sshkey',
                        url: 'git@github.com:tdtuan97/echarge-infras.git',
                        branch: 'main'

                    echo "Update chart"
                    withCredentials([file(credentialsId: env.KUBECONFIG_CREDENTIAL_ID, variable: 'KUBECONFIG')]) {
                        sh """
                            export KUBECONFIG=\${KUBECONFIG}

                            helm upgrade --install ${env.SERVICE_NAME} ${env.HELM_FOLDER} \\
                            --namespace ${env.K8S_NAMESPACE} \\
                            -f ${env.HELM_FOLDER}/${env.HELM_VALUES_FILE} \\
                            --set image.tag=${env.IMAGE_TAG}
                        """
                    }
                }
            }
        }
    }
}
